language: php

php:
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - redis-server

before_install:
  - mkdir cache -p
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar -q

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
