language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - redis-server

before_install:
  - mkdir cache
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - if [ $TRAVIS_TEST_RESULT == 0 ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
