language: php

php:
  - 5.5
  - 5.6
  - hhvm

services:
  - redis-server

before_install:
  - mkdir cache
  - composer install
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

script:
  - phpunit
